some changes to track plan error

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -54,6 +54,13 @@ jobs:
         run: terraform plan -no-color -input=false
         continue-on-error: true
 
-      - name: Terraform plan status
+      - name: Show plan logs on failure
         if: steps.plan.outcome == 'failure'
-        run: exit 1               
+        run: |
+          echo "Terraform plan failed, showing logs:"
+          terraform plan -no-color -input=false
+          exit 1
+
+      #- name: Terraform plan status
+      #  if: steps.plan.outcome == 'failure'
+      #  run: exit 1               
